language: java
jdk:
  - openjdk11

branches:
  only:
    - main # master 브런치에 push될 때 수행

# 같은 의존성은 캐싱처리를 할 디렉터리
cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.gradle'

# 프로젝트 내부의 gradlew을 통해 clean & build 수행
script: "./gradlew clean build"

# 1
before_deploy:
  - zip -r springboot-service *
  - mkdir -p deploy
  - mv springboot-service.zip deploy/springboot-service.zip

# 5
deploy:
  - provider: s3
    access_key_id: $AWS_ACCESS_KEY # Travis repo settings에 설정된 값
    secret_access_key: $AWS_SECRET_KEY # Travis repo settings에 설정된 값
    bucket: all-springboot-build    # S3 버킷
    region: ap-northeast-2
    skip_cleanup: true
    acl: private # zip 파일 접근을 private으로
    local_dir: deploy # before_deploy에서 생성한 디렉토리
    wait-until-deployed: true
    on:
      all_branches: true
  - provider: codedeploy
    access_key_id: $AWS_ACCESS_KEY # Travis repo settings에 설정된 값
    secret_access_key: $AWS_SECRET_KEY # Travis repo settings에 설정된 값
    bucket: all-springboot-build # S3 버킷
    key: springboot-service.zip # 빌드 파일을 압축해서 전달
    bundle_type: zip
    application: springboot-service # 웹 콘솔에서 등록한 CodeDeploy 어플리케이션
    deployment_group: springboot-service-group # 웹 콘솔에서 등록한 CodeDeploy 배포 그룹
    region: ap-northeast-2
    wait-until-deployed: true


# CI 실행 완료시 메일로 알람
notifications:
  email:
    recipients:
      - keepseung@gmail.com # 여기 바꿔도 됨!
